### ISSUE TITLE
Could use some doc comments

### ISSUE THREAD

**Issue by CreepySkeleton** [mtkennerly/realia#1]
This is how docs.rs currently looks like

![image](https://user-images.githubusercontent.com/50968528/87251242-d52c7d80-c472-11ea-891e-b3ff11b899b4.png)

![image](https://user-images.githubusercontent.com/50968528/87251258-e7a6b700-c472-11ea-98e3-65b1757c3d01.png)

That's a bit empty in there...

**Comment by mtkennerly** [comment]
Thanks for pointing this out. I didn't realize it would be uploaded automatically, so I hadn't really considered how it would look. I'll get this fixed up.

**Comment by mtkennerly** [comment]
This is now fixed in v0.1.1: https://docs.rs/realia/0.1.1/realia

> ![image](https://user-images.githubusercontent.com/4934192/87257325-19fee700-c468-11ea-9916-fdfc9fea9889.png)
